language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

licenses:
  - 'android-sdk-license-.+'

jdk: oraclejdk8

sudo: false

before_cache:
  - rm -rf $HOME/.m2/repository/io/michaelrocks/databindingcompat
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - yes | sdkmanager "platforms;android-28"

install:
  - ./gradlew assemble publishToMavenLocal -Pbootstrap=true --no-daemon --rerun-tasks

script:
  - ./gradlew check --no-daemon
